{% set name = "nionswift-usim" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76aa1e7145734a3d852844224bc733c3d9985a30ac2498d376ee19d1a8ba145b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - nionswift >=0.15.0
    - nionswift-instrumentation >=0.19.0

test:
  imports:
    - nionswift_plugin.usim
    - nionswift_plugin.usim.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift package to simulate a STEM microscope, scanner, and cameras
  dev_url: https://github.com/nion-software/nionswift-usim

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
